[workspace]
members = [
    "jupiter-swap-api-client",
    "example",
]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.80.0"

[workspace.dependencies]
solana-sdk = "2.2.1"
solana-client = "2.2.0"
solana-account-decoder = "2.2.0"
